Repository openshift/multus-cni, pull requests merged in 2019-08, with the labels that each got.

#20 Bug 1743587: Backporting "cni-version" in entrypoint.sh
  doc/how-to-use.md
  images/entrypoint.sh
  multus/multus.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#24 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#23 Bug 1732598: Adds one-shot CRIO restart
  doc/how-to-use.md
  images/entrypoint.sh
  images/multus-daemonset-crio.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/S
