Repository openshift/multus-cni, pull requests merged in 2019-11, with the labels that each got.

#34 build for rhel7 and rhel8 userspaces
  Dockerfile.openshift
Labels: approved, lgtm, size/S

#36 Bug 1725832: Skips binary copy in entrypoint with new parameter
  doc/how-to-use.md
  images/entrypoint.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#38 Installs git via yum for ART builds
  Dockerfile.openshift
Labels: approved, lgtm, size/XS

#39 sets a VERSION environment variable for RHEL8
  Dockerfile.openshift
Labels: approved, lgtm, size/XS

#40 Adds COMMIT environment variable, also required along with VERSION
  Dockerfile.openshift
Labels: approved, lgtm
