Repository openshift/multus-cni, pull requests merged in 2020-05, with the labels that each got.

#64 Bug 1826084: [backport 4.5] Sets the Kubernetes API calls timeout to 60 seconds
  k8sclient/k8sclient.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#66 Bug 1835037: Dev/remove git action
  .github/workflows/docker-build-push-master.yml
  .github/workflows/docker-build-push-release.yml
  .github/workflows/docker-build.yml
  .github/workflows/go-build-ppc64.yml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#65 Bug 1824940: Adds readinessindicatorfile check on CNI DEL
  multus/multus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#61 Bug 1827375: Allows allow pods in any namespace refer to net-attach-defs in default namespace
  doc/configuration.md
  k8sclient/k8sclient.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#67 Bug 1835033: Logging improvement (UID, net-attach-def) / Backport to 4.4
  k8sclient/k8sclient.go
  k8sclient/k8sclient_test.go
  multus/multus.go
  multus/multus_test.go
  testing/testing.go
  types/conf.go
  types/conf_test.go
  types/types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
