Repository openshift/multus-cni, pull requests merged in 2020-04, with the labels that each got.

#54 Adds readinessindicatorfile check on CNI DEL
  multus/multus.go
Labels: approved, lgtm

#58 Update OWNERS fields
  OWNERS
Labels: approved, lgtm

#59 Bug 1822803: Add nil check for pod in case of Eventf()
  go.mod
  go.sum
  multus/multus.go
  webhook/Dockerfile
  webhook/build
  webhook/glide.yaml
  webhook/webhook.go
  webhook/webhook_suite_test.go
  webhook/webhook_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#60 Bug 1827377: Allows allow pods in any namespace refer to net-attach-defs in default namespace
  doc/configuration.md
  k8sclient/k8sclient.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm
