Repository openshift/multus-cni, pull requests merged in 2021-06, with the labels that each got.

#102 Bug 1968625: Use the default socket path in GetResourceClient when unspecified
  pkg/kubeletclient/kubeletclient.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#100 Added reviewer nicklesimba
  OWNERS
Labels: approved, lgtm, ok-to-test

#107 Bug 1973423: Updates entrypoint to rebuild kubeconfig when service account token or ca changes
  images/entrypoint.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#108 Bug 1972167: Updates entrypoint to rebuild kubeconfig when service account token or ca changes
  images/entrypoint.sh
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm
