Repository openshift/multus-cni, pull requests merged in 2024-01, with the labels that each got.

#205 OCPBUGS-26222: Adds a wait on unix socket readiness
  cmd/cert-approver/main.go
  cmd/multus-daemon/main.go
  cmd/thin_entrypoint/main_test.go
  pkg/server/api/api.go
  pkg/server/api/shim.go
  pkg/server/config/config_suite_test.go
  pkg/server/config/generator_test.go
  pkg/server/config/manager_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#206 OCPBUGS-22839: Adds a wait on unix socket readiness [backport 4.15]
  cmd/cert-approver/main.go
  cmd/multus-daemon/main.go
  cmd/thin_entrypoint/main_test.go
  pkg/server/api/api.go
  pkg/server/api/shim.go
  pkg/server/config/config_suite_test.go
  pkg/server/config/generator_test.go
  pkg/server/config/manager_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#207 OCPBUGS-26397: Revert #205 "Adds a wait on unix socket readiness"
  cmd/cert-approver/main.go
  cmd/multus-daemon/main.go
  cmd/thin_entrypoint/main_test.go
  pkg/server/api/api.go
  pkg/server/api/shim.go
  pkg/server/config/config_suite_test.go
  pkg/server/config/generator_test.go
  pkg/server/config/manager_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#209 OCPBUGS-26535: Revert #206 "Adds a wait on unix socket readiness [backport 4.15]"
  cmd/cert-approver/main.go
  cmd/multus-daemon/main.go
  cmd/thin_entrypoint/main_test.go
  pkg/server/api/api.go
  pkg/server/api/shim.go
  pkg/server/config/config_suite_test.go
  pkg/server/config/generator_test.go
  pkg/server/config/manager_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#208 OCPBUGS-26222: Adds a wait to account for the possiblity of a not ready unix socket
  cmd/cert-approver/main.go
  cmd/multus-daemon/main.go
  pkg/server/api/api.go
  pkg/server/api/shim.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#210 OCPBUGS-22839: Adds a wait on unix socket readiness [backport 4.15]
  cmd/cert-approver/main.go
  cmd/multus-daemon/main.go
  pkg/server/api/api.go
  pkg/server/api/shim.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
