Repository openshift/multus-cni, pull requests merged in 2024-06, with the labels that each got.

#233 OCPBUGS-33559: Thick plugin should not wait for API readiness on CNI DEL
  pkg/server/api/api.go
  pkg/server/api/shim.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#237 OCPBUGS-34911: Update owners file
  OWNERS
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#241 OKD-218: install util-linux
  Dockerfile.microshift
  Dockerfile.openshift
Labels: lgtm, approved, jira/valid-reference
